sylius_grid:
    grids:
        setono_sylius_webhook_admin_incoming_webhook:
            driver:
                options:
                    class: "%setono_sylius_webhook.model.incoming_webhook.class%"
            sorting:
                receivedAt: desc
            limits: [100, 250, 500, 1000]
            fields:
                id:
                    type: string
                    label: sylius.ui.id
                endpoint:
                    type: string
                    label: setono_sylius_webhook.ui.endpoint
                state:
                    type: string
                    label: setono_sylius_webhook.ui.state
                    sortable: ~
                error:
                    type: string
                    label: setono_sylius_webhook.ui.error
                receivedAt:
                    type: datetime
                    label: setono_sylius_webhook.ui.received_at
                    sortable: ~
            actions:
                item:
                    show:
                        type: show
                        label: sylius.ui.show
