setono_sylius_webhook_admin_endpoint:
    resource: |
        section: admin
        alias: setono_sylius_webhook.endpoint
        templates: "@SyliusAdmin\\Crud"
        redirect: update
        permission: true
        grid: setono_sylius_webhook_admin_endpoint
        vars:
            all:
                header: setono_sylius_webhook.ui.endpoint_header
                subheader: setono_sylius_webhook.ui.endpoint_subheader
    type: sylius.resource
    
setono_sylius_webhook_admin_incoming_webhook:
    resource: |
        section: admin
        alias: setono_sylius_webhook.incoming_webhook
        templates: "@SyliusAdmin\\Crud"
        redirect: update
        permission: true
        grid: setono_sylius_webhook_admin_incoming_webhook
        vars:
            all:
                header: setono_sylius_webhook.ui.incoming_webhook_header
                subheader: setono_sylius_webhook.ui.incoming_webhook_subheader
    type: sylius.resource
    
setono_sylius_webhook_admin_incoming_webhook_show:
    path: /incoming-webhooks/{id}
    methods: [GET]
    defaults:
        _controller: setono_sylius_webhook.controller.incoming_webhook:showAction
        _sylius:
            section: admin
            permission: true
            template: "@SetonoSyliusWebhookPlugin/admin/incoming_webhook/show.html.twig"
