setono_sylius_webhook_shop_handle_incoming_webhook_request:
    path: /webhooks/{code}
    methods: [GET,POST]
    defaults:
        _controller: setono_sylius_webhook.controller.action.handle_incoming_webhook
    requirements:
        code: '[a-zA-Z0-9-_]+'
